url: https://robot-dreams-de-api.herokuapp.com
endpoints:
  auth:
    address: /auth
    timeout: 5
  out_of_stock:
    address: /out_of_stock
    timeout: 5
auth_data:
  username: rd_dreams
  password: djT6LasE
data_directory: data